/* This file is generated by vcl-protocol.  See vcl_protocol_driver.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use vcl_opencl_gen::*;

use super::*;

use std::ptr;
use std::ffi::*;



pub fn vcl_sizeof_clRetainContext(context: cl_context, ) -> usize {
    let cmd_type: ClCommandTypeExt = ClCommandTypeExt::RetainContext;
    let cmd_flags = ClCommandFlagBitsExt::default();
    let mut cmd_size = vcl_sizeof_ClCommandTypeExt(&cmd_type);
    cmd_size += vcl_sizeof_ClCommandFlagBitsExt(&cmd_flags);

    cmd_size += vcl_sizeof_cl_context(&context);

    cmd_size
}

impl<'b> VclCsEncoder<'b> {
    pub fn encode_clRetainContext(&mut self, cmd_flags: ClCommandFlagBitsExt, context: cl_context, )
    {
        let cmd_type: ClCommandTypeExt = ClCommandTypeExt::RetainContext;

        self.encode_ClCommandTypeExt(&cmd_type);
        self.encode_ClCommandFlagBitsExt(&cmd_flags);

        self.encode_cl_context(&context);
    }
}

pub fn vcl_sizeof_clRetainContext_reply(context: cl_context, ) -> usize {
    let cmd_type: ClCommandTypeExt = ClCommandTypeExt::RetainContext;
    let mut cmd_size = 0;
    cmd_size += vcl_sizeof_ClCommandTypeExt(&cmd_type);

    let ret: cl_int = vcl_default_cl_int();
    cmd_size += vcl_sizeof_cl_int(&ret);
    /* skip context */

    cmd_size
}

impl VclCsDecoder {
    pub fn decode_clRetainContext_reply(&mut self, context: cl_context, ) -> cl_int {
        let mut command_type = ClCommandTypeExt::default();
        self.decode_ClCommandTypeExt(&mut command_type);
        assert_eq!(command_type, ClCommandTypeExt::RetainContext);

        let mut ret: cl_int = vcl_default_cl_int();
        self.decode_cl_int(&mut ret);
        /* skip context */

        ret
    }
}

pub fn vcl_sizeof_clReleaseContext(context: cl_context, ) -> usize {
    let cmd_type: ClCommandTypeExt = ClCommandTypeExt::ReleaseContext;
    let cmd_flags = ClCommandFlagBitsExt::default();
    let mut cmd_size = vcl_sizeof_ClCommandTypeExt(&cmd_type);
    cmd_size += vcl_sizeof_ClCommandFlagBitsExt(&cmd_flags);

    cmd_size += vcl_sizeof_cl_context(&context);

    cmd_size
}

impl<'b> VclCsEncoder<'b> {
    pub fn encode_clReleaseContext(&mut self, cmd_flags: ClCommandFlagBitsExt, context: cl_context, )
    {
        let cmd_type: ClCommandTypeExt = ClCommandTypeExt::ReleaseContext;

        self.encode_ClCommandTypeExt(&cmd_type);
        self.encode_ClCommandFlagBitsExt(&cmd_flags);

        self.encode_cl_context(&context);
    }
}

pub fn vcl_sizeof_clReleaseContext_reply(context: cl_context, ) -> usize {
    let cmd_type: ClCommandTypeExt = ClCommandTypeExt::ReleaseContext;
    let mut cmd_size = 0;
    cmd_size += vcl_sizeof_ClCommandTypeExt(&cmd_type);

    let ret: cl_int = vcl_default_cl_int();
    cmd_size += vcl_sizeof_cl_int(&ret);
    /* skip context */

    cmd_size
}

impl VclCsDecoder {
    pub fn decode_clReleaseContext_reply(&mut self, context: cl_context, ) -> cl_int {
        let mut command_type = ClCommandTypeExt::default();
        self.decode_ClCommandTypeExt(&mut command_type);
        assert_eq!(command_type, ClCommandTypeExt::ReleaseContext);

        let mut ret: cl_int = vcl_default_cl_int();
        self.decode_cl_int(&mut ret);
        /* skip context */

        ret
    }
}

pub fn vcl_sizeof_clGetContextInfo(context: cl_context, param_name: cl_context_info, param_value_size: usize, param_value: *mut c_void, param_value_size_ret: *mut usize, ) -> usize {
    let cmd_type: ClCommandTypeExt = ClCommandTypeExt::GetContextInfo;
    let cmd_flags = ClCommandFlagBitsExt::default();
    let mut cmd_size = vcl_sizeof_ClCommandTypeExt(&cmd_type);
    cmd_size += vcl_sizeof_ClCommandFlagBitsExt(&cmd_flags);

    cmd_size += vcl_sizeof_cl_context(&context);
    cmd_size += vcl_sizeof_cl_context_info(&param_name);
    cmd_size += vcl_sizeof_usize(&param_value_size);
    cmd_size += vcl_sizeof_simple_pointer(param_value as _); /* out */
    cmd_size += vcl_sizeof_simple_pointer(param_value_size_ret as _); /* out */

    cmd_size
}

impl<'b> VclCsEncoder<'b> {
    pub fn encode_clGetContextInfo(&mut self, cmd_flags: ClCommandFlagBitsExt, context: cl_context, param_name: cl_context_info, param_value_size: usize, param_value: *mut c_void, param_value_size_ret: *mut usize, )
    {
        let cmd_type: ClCommandTypeExt = ClCommandTypeExt::GetContextInfo;

        self.encode_ClCommandTypeExt(&cmd_type);
        self.encode_ClCommandFlagBitsExt(&cmd_flags);

        self.encode_cl_context(&context);
        self.encode_cl_context_info(&param_name);
        self.encode_usize(&param_value_size);
        self.encode_array_size(if param_value != ptr::null_mut() { param_value_size as u64 } else { 0 }); /* out */
        self.encode_simple_pointer(param_value_size_ret as _); /* out */
    }
}

pub fn vcl_sizeof_clGetContextInfo_reply(context: cl_context, param_name: cl_context_info, param_value_size: usize, param_value: *mut c_void, param_value_size_ret: *mut usize, ) -> usize {
    let cmd_type: ClCommandTypeExt = ClCommandTypeExt::GetContextInfo;
    let mut cmd_size = 0;
    cmd_size += vcl_sizeof_ClCommandTypeExt(&cmd_type);

    let ret: cl_int = vcl_default_cl_int();
    cmd_size += vcl_sizeof_cl_int(&ret);
    /* skip context */
    /* skip param_name */
    /* skip param_value_size */
    if param_value != ptr::null_mut() {
        cmd_size += vcl_sizeof_array_size(param_value_size as u64);
        cmd_size += vcl_sizeof_blob_array(param_value, param_value_size as _);
    } else {
        cmd_size += vcl_sizeof_array_size(0);
    }
    cmd_size += vcl_sizeof_simple_pointer(param_value_size_ret as _);
    if param_value_size_ret != ptr::null_mut() {
        cmd_size += vcl_sizeof_usize(param_value_size_ret);
    }

    cmd_size
}

impl VclCsDecoder {
    pub fn decode_clGetContextInfo_reply(&mut self, context: cl_context, param_name: cl_context_info, param_value_size: usize, param_value: *mut c_void, param_value_size_ret: *mut usize, ) -> cl_int {
        let mut command_type = ClCommandTypeExt::default();
        self.decode_ClCommandTypeExt(&mut command_type);
        assert_eq!(command_type, ClCommandTypeExt::GetContextInfo);

        let mut ret: cl_int = vcl_default_cl_int();
        self.decode_cl_int(&mut ret);
        /* skip context */
        /* skip param_name */
        /* skip param_value_size */
        if self.peek_array_size() > 0 {
            let array_size = self.decode_array_size(param_value_size as _) as usize;
                self.decode_blob_array(param_value, array_size as _);
        } else {
            self.decode_array_size_unchecked();
            //param_value = ptr::null_mut();
        }
        if self.decode_simple_pointer() {
            self.decode_usize(param_value_size_ret);
        } else {
            //param_value_size_ret = ptr::null_mut();
        }

        ret
    }
}

pub fn vcl_sizeof_clCreateContextMESA(properties: *const cl_context_properties, num_devices: cl_uint, devices: *const cl_device_id, user_data: *mut c_void, context: *mut cl_context, ) -> usize {
    let cmd_type: ClCommandTypeExt = ClCommandTypeExt::CreateContextMESA;
    let cmd_flags = ClCommandFlagBitsExt::default();
    let mut cmd_size = vcl_sizeof_ClCommandTypeExt(&cmd_type);
    cmd_size += vcl_sizeof_ClCommandFlagBitsExt(&cmd_flags);

    if properties != ptr::null() {
        let null_terminated_array_size: usize = properties.as_slice_with_null().len();
        cmd_size += vcl_sizeof_array_size(null_terminated_array_size as u64);
        cmd_size += vcl_sizeof_cl_context_properties_array(properties.as_slice_with_null().as_ptr(), null_terminated_array_size);
    } else {
        cmd_size += vcl_sizeof_array_size(0);
    }
    cmd_size += vcl_sizeof_cl_uint(&num_devices);
    cmd_size += vcl_sizeof_simple_pointer(devices as _);
    if devices != ptr::null_mut() {
        cmd_size += vcl_sizeof_cl_device_id(devices);
    }
    cmd_size += vcl_sizeof_simple_pointer(user_data as _); /* out */
    cmd_size += vcl_sizeof_simple_pointer(context as _);
    if context != ptr::null_mut() {
        cmd_size += vcl_sizeof_cl_context(context);
    }

    cmd_size
}

impl<'b> VclCsEncoder<'b> {
    pub fn encode_clCreateContextMESA(&mut self, cmd_flags: ClCommandFlagBitsExt, properties: *const cl_context_properties, num_devices: cl_uint, devices: *const cl_device_id, user_data: *mut c_void, context: *mut cl_context, )
    {
        let cmd_type: ClCommandTypeExt = ClCommandTypeExt::CreateContextMESA;

        self.encode_ClCommandTypeExt(&cmd_type);
        self.encode_ClCommandFlagBitsExt(&cmd_flags);

        if properties != ptr::null_mut() {
            let array_size = properties.as_slice_with_null().len();
            self.encode_array_size(array_size as _);
            self.encode_cl_context_properties_array(properties.as_slice_with_null().as_ptr(), array_size);
        } else {
            self.encode_array_size(0);
        }
        self.encode_cl_uint(&num_devices);
        if self.encode_simple_pointer(devices as _) {
            self.encode_cl_device_id(devices);
        }
        self.encode_simple_pointer(user_data as _); /* out */
        if self.encode_simple_pointer(context as _) {
            self.encode_cl_context(context);
        }
    }
}

pub fn vcl_sizeof_clCreateContextMESA_reply(properties: *const cl_context_properties, num_devices: cl_uint, devices: *const cl_device_id, user_data: *mut c_void, context: *mut cl_context, ) -> usize {
    let cmd_type: ClCommandTypeExt = ClCommandTypeExt::CreateContextMESA;
    let mut cmd_size = 0;
    cmd_size += vcl_sizeof_ClCommandTypeExt(&cmd_type);

    let ret: cl_int = vcl_default_cl_int();
    cmd_size += vcl_sizeof_cl_int(&ret);
    /* skip properties */
    /* skip num_devices */
    /* skip devices */
    cmd_size += vcl_sizeof_simple_pointer(user_data as _);
    if user_data != ptr::null_mut() {
        assert!(false);
    }
    cmd_size += vcl_sizeof_simple_pointer(context as _);
    if context != ptr::null_mut() {
        cmd_size += vcl_sizeof_cl_context(context);
    }

    cmd_size
}

impl VclCsDecoder {
    pub fn decode_clCreateContextMESA_reply(&mut self, properties: *const cl_context_properties, num_devices: cl_uint, devices: *const cl_device_id, user_data: *mut c_void, context: *mut cl_context, ) -> cl_int {
        let mut command_type = ClCommandTypeExt::default();
        self.decode_ClCommandTypeExt(&mut command_type);
        assert_eq!(command_type, ClCommandTypeExt::CreateContextMESA);

        let mut ret: cl_int = vcl_default_cl_int();
        self.decode_cl_int(&mut ret);
        /* skip properties */
        /* skip num_devices */
        /* skip devices */
        if self.decode_simple_pointer() {
            assert!(false);
        } else {
            //user_data = ptr::null_mut();
        }
        if self.decode_simple_pointer() {
            self.decode_cl_context(context);
        } else {
            //context = ptr::null_mut();
        }

        ret
    }
}

impl Vcl {
    pub fn submit_clRetainContext(&self, cmd_flags: ClCommandFlagBitsExt, context: cl_context, ) -> CLResult<Option<VclCsDecoder>> {
        let mut local_cmd_data = [0u8; VCL_SUBMIT_LOCAL_CMD_SIZE];
        let mut cmd_data = local_cmd_data.as_mut_slice();
        let mut heap_cmd_data;

        let mut cmd_size = vcl_sizeof_clRetainContext(context, );
        if cmd_size <= 0 {
            return Ok(None);
        }

        let reply_size = if cmd_flags & ClCommandFlagBitsExt::GenerateReplyBit {
             vcl_sizeof_clRetainContext_reply(context, )
        } else {
            0
        };

        if reply_size > 0 {
            // In case we need to generate the reply, we need to encode the set
            // reply buffer command, so let us make space for it
            cmd_size += vcl_sizeof_clSetReplyBufferMESA(0);
        }

        if cmd_size > VCL_SUBMIT_LOCAL_CMD_SIZE {
            heap_cmd_data = Some(vec![0u8; cmd_size]);
            cmd_data = heap_cmd_data.as_mut().unwrap().as_mut_slice();
        }

        let mut enc = VclCsEncoder::new(cmd_data);

        let reply_buf = if reply_size > 0 {
            let buf = self.renderer.create_buffer(reply_size)?;
            enc.encode_clSetReplyBufferMESA(ClCommandFlagBitsExt::Empty, buf.get_handle());
            Some(buf)
        } else {
            None
        };

        enc.encode_clRetainContext(cmd_flags, context, );
        self.renderer.submit(enc)?;
        if let Some(mut reply_buf) = reply_buf {
            self.renderer.transfer_get(reply_buf.res.as_mut())?;
            Ok(Some(VclCsDecoder::new(reply_buf)))
        } else {
            Ok(None)
        }

    }
}

impl Vcl {
    pub fn submit_clReleaseContext(&self, cmd_flags: ClCommandFlagBitsExt, context: cl_context, ) -> CLResult<Option<VclCsDecoder>> {
        let mut local_cmd_data = [0u8; VCL_SUBMIT_LOCAL_CMD_SIZE];
        let mut cmd_data = local_cmd_data.as_mut_slice();
        let mut heap_cmd_data;

        let mut cmd_size = vcl_sizeof_clReleaseContext(context, );
        if cmd_size <= 0 {
            return Ok(None);
        }

        let reply_size = if cmd_flags & ClCommandFlagBitsExt::GenerateReplyBit {
             vcl_sizeof_clReleaseContext_reply(context, )
        } else {
            0
        };

        if reply_size > 0 {
            // In case we need to generate the reply, we need to encode the set
            // reply buffer command, so let us make space for it
            cmd_size += vcl_sizeof_clSetReplyBufferMESA(0);
        }

        if cmd_size > VCL_SUBMIT_LOCAL_CMD_SIZE {
            heap_cmd_data = Some(vec![0u8; cmd_size]);
            cmd_data = heap_cmd_data.as_mut().unwrap().as_mut_slice();
        }

        let mut enc = VclCsEncoder::new(cmd_data);

        let reply_buf = if reply_size > 0 {
            let buf = self.renderer.create_buffer(reply_size)?;
            enc.encode_clSetReplyBufferMESA(ClCommandFlagBitsExt::Empty, buf.get_handle());
            Some(buf)
        } else {
            None
        };

        enc.encode_clReleaseContext(cmd_flags, context, );
        self.renderer.submit(enc)?;
        if let Some(mut reply_buf) = reply_buf {
            self.renderer.transfer_get(reply_buf.res.as_mut())?;
            Ok(Some(VclCsDecoder::new(reply_buf)))
        } else {
            Ok(None)
        }

    }
}

impl Vcl {
    pub fn submit_clGetContextInfo(&self, cmd_flags: ClCommandFlagBitsExt, context: cl_context, param_name: cl_context_info, param_value_size: usize, param_value: *mut c_void, param_value_size_ret: *mut usize, ) -> CLResult<Option<VclCsDecoder>> {
        let mut local_cmd_data = [0u8; VCL_SUBMIT_LOCAL_CMD_SIZE];
        let mut cmd_data = local_cmd_data.as_mut_slice();
        let mut heap_cmd_data;

        let mut cmd_size = vcl_sizeof_clGetContextInfo(context, param_name, param_value_size, param_value, param_value_size_ret, );
        if cmd_size <= 0 {
            return Ok(None);
        }

        let reply_size = if cmd_flags & ClCommandFlagBitsExt::GenerateReplyBit {
             vcl_sizeof_clGetContextInfo_reply(context, param_name, param_value_size, param_value, param_value_size_ret, )
        } else {
            0
        };

        if reply_size > 0 {
            // In case we need to generate the reply, we need to encode the set
            // reply buffer command, so let us make space for it
            cmd_size += vcl_sizeof_clSetReplyBufferMESA(0);
        }

        if cmd_size > VCL_SUBMIT_LOCAL_CMD_SIZE {
            heap_cmd_data = Some(vec![0u8; cmd_size]);
            cmd_data = heap_cmd_data.as_mut().unwrap().as_mut_slice();
        }

        let mut enc = VclCsEncoder::new(cmd_data);

        let reply_buf = if reply_size > 0 {
            let buf = self.renderer.create_buffer(reply_size)?;
            enc.encode_clSetReplyBufferMESA(ClCommandFlagBitsExt::Empty, buf.get_handle());
            Some(buf)
        } else {
            None
        };

        enc.encode_clGetContextInfo(cmd_flags, context, param_name, param_value_size, param_value, param_value_size_ret, );
        self.renderer.submit(enc)?;
        if let Some(mut reply_buf) = reply_buf {
            self.renderer.transfer_get(reply_buf.res.as_mut())?;
            Ok(Some(VclCsDecoder::new(reply_buf)))
        } else {
            Ok(None)
        }

    }
}

impl Vcl {
    pub fn submit_clCreateContextMESA(&self, cmd_flags: ClCommandFlagBitsExt, properties: *const cl_context_properties, num_devices: cl_uint, devices: *const cl_device_id, user_data: *mut c_void, context: *mut cl_context, ) -> CLResult<Option<VclCsDecoder>> {
        let mut local_cmd_data = [0u8; VCL_SUBMIT_LOCAL_CMD_SIZE];
        let mut cmd_data = local_cmd_data.as_mut_slice();
        let mut heap_cmd_data;

        let mut cmd_size = vcl_sizeof_clCreateContextMESA(properties, num_devices, devices, user_data, context, );
        if cmd_size <= 0 {
            return Ok(None);
        }

        let reply_size = if cmd_flags & ClCommandFlagBitsExt::GenerateReplyBit {
             vcl_sizeof_clCreateContextMESA_reply(properties, num_devices, devices, user_data, context, )
        } else {
            0
        };

        if reply_size > 0 {
            // In case we need to generate the reply, we need to encode the set
            // reply buffer command, so let us make space for it
            cmd_size += vcl_sizeof_clSetReplyBufferMESA(0);
        }

        if cmd_size > VCL_SUBMIT_LOCAL_CMD_SIZE {
            heap_cmd_data = Some(vec![0u8; cmd_size]);
            cmd_data = heap_cmd_data.as_mut().unwrap().as_mut_slice();
        }

        let mut enc = VclCsEncoder::new(cmd_data);

        let reply_buf = if reply_size > 0 {
            let buf = self.renderer.create_buffer(reply_size)?;
            enc.encode_clSetReplyBufferMESA(ClCommandFlagBitsExt::Empty, buf.get_handle());
            Some(buf)
        } else {
            None
        };

        enc.encode_clCreateContextMESA(cmd_flags, properties, num_devices, devices, user_data, context, );
        self.renderer.submit(enc)?;
        if let Some(mut reply_buf) = reply_buf {
            self.renderer.transfer_get(reply_buf.res.as_mut())?;
            Ok(Some(VclCsDecoder::new(reply_buf)))
        } else {
            Ok(None)
        }

    }
}

impl Vcl {
    pub fn call_clRetainContext(&self, context: cl_context, ) -> Result<(), cl_int> {
        let dec = self.submit_clRetainContext(ClCommandFlagBitsExt::GenerateReplyBit, context, )?;
        if let Some(mut dec) = dec {
            let ret = dec.decode_clRetainContext_reply(context);
            if ret != CL_SUCCESS as _ {
                return Err(ret);
            } else {
                return Ok(());
            }
        } else {
            return Err(CL_OUT_OF_HOST_MEMORY);
        }
    }
}

impl Vcl {
    pub fn async_clRetainContext(&self, context: cl_context, ) -> CLResult<()> {
        self.submit_clRetainContext(Default::default(), context, )?;
        Ok(())
    }
}

impl Vcl {
    pub fn call_clReleaseContext(&self, context: cl_context, ) -> Result<(), cl_int> {
        let dec = self.submit_clReleaseContext(ClCommandFlagBitsExt::GenerateReplyBit, context, )?;
        if let Some(mut dec) = dec {
            let ret = dec.decode_clReleaseContext_reply(context);
            if ret != CL_SUCCESS as _ {
                return Err(ret);
            } else {
                return Ok(());
            }
        } else {
            return Err(CL_OUT_OF_HOST_MEMORY);
        }
    }
}

impl Vcl {
    pub fn async_clReleaseContext(&self, context: cl_context, ) -> CLResult<()> {
        self.submit_clReleaseContext(Default::default(), context, )?;
        Ok(())
    }
}

impl Vcl {
    pub fn call_clGetContextInfo(&self, context: cl_context, param_name: cl_context_info, param_value_size: usize, param_value: *mut c_void, param_value_size_ret: *mut usize, ) -> Result<(), cl_int> {
        let dec = self.submit_clGetContextInfo(ClCommandFlagBitsExt::GenerateReplyBit, context, param_name, param_value_size, param_value, param_value_size_ret, )?;
        if let Some(mut dec) = dec {
            let ret = dec.decode_clGetContextInfo_reply(context, param_name, param_value_size, param_value, param_value_size_ret);
            if ret != CL_SUCCESS as _ {
                return Err(ret);
            } else {
                return Ok(());
            }
        } else {
            return Err(CL_OUT_OF_HOST_MEMORY);
        }
    }
}

impl Vcl {
    pub fn async_clGetContextInfo(&self, context: cl_context, param_name: cl_context_info, param_value_size: usize, param_value: *mut c_void, param_value_size_ret: *mut usize, ) -> CLResult<()> {
        self.submit_clGetContextInfo(Default::default(), context, param_name, param_value_size, param_value, param_value_size_ret, )?;
        Ok(())
    }
}

impl Vcl {
    pub fn call_clCreateContextMESA(&self, properties: *const cl_context_properties, num_devices: cl_uint, devices: *const cl_device_id, user_data: *mut c_void, context: *mut cl_context, ) -> Result<(), cl_int> {
        let dec = self.submit_clCreateContextMESA(ClCommandFlagBitsExt::GenerateReplyBit, properties, num_devices, devices, user_data, context, )?;
        if let Some(mut dec) = dec {
            let ret = dec.decode_clCreateContextMESA_reply(properties, num_devices, devices, user_data, context);
            if ret != CL_SUCCESS as _ {
                return Err(ret);
            } else {
                return Ok(());
            }
        } else {
            return Err(CL_OUT_OF_HOST_MEMORY);
        }
    }
}

impl Vcl {
    pub fn async_clCreateContextMESA(&self, properties: *const cl_context_properties, num_devices: cl_uint, devices: *const cl_device_id, user_data: *mut c_void, context: *mut cl_context, ) -> CLResult<()> {
        self.submit_clCreateContextMESA(Default::default(), properties, num_devices, devices, user_data, context, )?;
        Ok(())
    }
}

