/* This file is generated by vcl-protocol.  See vcl_protocol_driver.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */


pub const VCL_SUBMIT_LOCAL_CMD_SIZE: usize = 256;

#[repr(u32)]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub enum ClCommandTypeExt {
    #[default]
    GetPlatformIDs = 0,
    GetPlatformInfo = 1,
    GetDeviceIDs = 2,
    GetDeviceInfo = 3,
    CreateSubDevices = 4,
    RetainDevice = 5,
    ReleaseDevice = 6,
    SetDefaultDeviceCommandQueue = 7,
    GetDeviceAndHostTimer = 8,
    GetHostTimer = 9,
    CreateContext = 10,
    CreateContextFromType = 11,
    RetainContext = 12,
    ReleaseContext = 13,
    GetContextInfo = 14,
    SetContextDestructorCallback = 15,
    CreateCommandQueueWithProperties = 16,
    RetainCommandQueue = 17,
    ReleaseCommandQueue = 18,
    GetCommandQueueInfo = 19,
    CreateBuffer = 20,
    CreateBufferWithProperties = 21,
    CreateSubBuffer = 22,
    CreateImage = 23,
    CreateImageWithProperties = 24,
    CreatePipe = 25,
    RetainMemObject = 26,
    ReleaseMemObject = 27,
    GetSupportedImageFormats = 28,
    GetMemObjectInfo = 29,
    GetImageInfo = 30,
    GetPipeInfo = 31,
    SetMemObjectDestructorCallback = 32,
    SVMAlloc = 33,
    SVMFree = 34,
    CreateSamplerWithProperties = 35,
    RetainSampler = 36,
    ReleaseSampler = 37,
    GetSamplerInfo = 38,
    CreateProgramWithSource = 39,
    CreateProgramWithBinary = 40,
    CreateProgramWithBuiltInKernels = 41,
    CreateProgramWithIL = 42,
    RetainProgram = 43,
    ReleaseProgram = 44,
    BuildProgram = 45,
    CompileProgram = 46,
    LinkProgram = 47,
    SetProgramReleaseCallback = 48,
    SetProgramSpecializationConstant = 49,
    UnloadPlatformCompiler = 50,
    GetProgramInfo = 51,
    GetProgramBuildInfo = 52,
    CreateKernel = 53,
    CreateKernelsInProgram = 54,
    CloneKernel = 55,
    RetainKernel = 56,
    ReleaseKernel = 57,
    SetKernelArg = 58,
    SetKernelArgSVMPointer = 59,
    SetKernelExecInfo = 60,
    GetKernelInfo = 61,
    GetKernelArgInfo = 62,
    GetKernelWorkGroupInfo = 63,
    GetKernelSubGroupInfo = 64,
    WaitForEvents = 65,
    GetEventInfo = 66,
    CreateUserEvent = 67,
    RetainEvent = 68,
    ReleaseEvent = 69,
    SetUserEventStatus = 70,
    SetEventCallback = 71,
    GetEventProfilingInfo = 72,
    Flush = 73,
    Finish = 74,
    EnqueueReadBuffer = 75,
    EnqueueReadBufferRect = 76,
    EnqueueWriteBuffer = 77,
    EnqueueWriteBufferRect = 78,
    EnqueueFillBuffer = 79,
    EnqueueCopyBuffer = 80,
    EnqueueCopyBufferRect = 81,
    EnqueueReadImage = 82,
    EnqueueWriteImage = 83,
    EnqueueFillImage = 84,
    EnqueueCopyImage = 85,
    EnqueueCopyImageToBuffer = 86,
    EnqueueCopyBufferToImage = 87,
    EnqueueMapBuffer = 88,
    EnqueueMapImage = 89,
    EnqueueUnmapMemObject = 90,
    EnqueueMigrateMemObjects = 91,
    EnqueueNDRangeKernel = 92,
    EnqueueNativeKernel = 93,
    EnqueueMarkerWithWaitList = 94,
    EnqueueBarrierWithWaitList = 95,
    EnqueueSVMFree = 96,
    EnqueueSVMMemcpy = 97,
    EnqueueSVMMemFill = 98,
    EnqueueSVMMap = 99,
    EnqueueSVMUnmap = 100,
    EnqueueSVMMigrateMem = 101,
    GetExtensionFunctionAddressForPlatform = 102,
    SetCommandQueueProperty = 103,
    CreateImage2D = 104,
    CreateImage3D = 105,
    EnqueueMarker = 106,
    EnqueueWaitForEvents = 107,
    EnqueueBarrier = 108,
    UnloadCompiler = 109,
    GetExtensionFunctionAddress = 110,
    CreateCommandQueue = 111,
    CreateSampler = 112,
    EnqueueTask = 113,
    EnqueueNDRangeKernelMESA = 229,
    EnqueueMapImageMESA = 230,
    EnqueueUnmapMemObjectMESA = 231,
    EnqueueMapBufferMESA = 232,
    EnqueueReadImageMESA = 233,
    EnqueueWriteImageMESA = 234,
    EnqueueFillImageMESA = 235,
    CreateImageMESA = 236,
    CreateImageWithPropertiesMESA = 237,
    CreateSubBufferMESA = 238,
    CreateImage3DMESA = 239,
    CreateSamplerWithPropertiesMESA = 240,
    CreateSamplerMESA = 241,
    LinkProgramMESA = 242,
    CreateProgramWithILMESA = 243,
    CreateProgramWithBinaryMESA = 244,
    CreateProgramWithSourceMESA = 245,
    CreateKernelMESA = 246,
    CloneKernelMESA = 247,
    CreateImage2DMESA = 248,
    CreateBufferMESA = 249,
    CreateBufferWithPropertiesMESA = 250,
    CreateUserEventMESA = 251,
    CreateContextMESA = 252,
    CreateCommandQueueMESA = 253,
    CreateCommandQueueWithPropertiesMESA = 254,
    SetReplyBufferMESA = 255,
}

impl std::ops::BitAnd for ClCommandTypeExt {
    type Output = bool;

    // rhs is the "right-hand side" of the expression `a & b`
    fn bitand(self, rhs: Self) -> Self::Output {
        (self as u32 & rhs as u32) != 0
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub enum ClCommandFlagBitsExt {
    #[default]
    Empty = 0x00000000,
    GenerateReplyBit = 0x00000001,
}

impl std::ops::BitAnd for ClCommandFlagBitsExt {
    type Output = bool;

    // rhs is the "right-hand side" of the expression `a & b`
    fn bitand(self, rhs: Self) -> Self::Output {
        (self as u32 & rhs as u32) != 0
    }
}

