/* This file is generated by vcl-protocol.  See vcl_protocol_driver.h. */

/*
 * Copyright 2020 Google LLC
 * Copyright 2024 Qualcomm Innovation Center, Inc. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */



pub struct VclInfoExtension {
   pub name: &'static str,
   pub number: u32,
   pub spec_version: u32,
}

/* sorted by extension names for bsearch */
const _VCL_INFO_EXTENSION_COUNT: u32 = 2;
const _VCL_INFO_EXTENSIONS: [VclInfoExtension; 2] = [
   VclInfoExtension { name: "CL_EXT_command_serialization", number: 42, spec_version: 1 },
   VclInfoExtension { name: "CL_MESA_vcl_protocol", number: 42, spec_version: 0 },
];



